### ISSUE TITLE
Use vim.loop.cwd & allow for child files to be found

### ISSUE THREAD

**Issue by tami5** [shoumodip/ido.nvim#1]
Hey @shoumodip , Interesting plugin, It brought back some good memorizes. I really do like such interface. Hope to see this port mature and become more stable.

Not sure if you accept a prs yet, or this project something serious you intend to work on longer term, but here is a better way to get current working directory and its very fast. I think its better then being taken from current buffer, but an option to let the user decide would be nice.

```diff
-  if dirname == nil then
-    if vim.fn.expand('%:p') == '' then
-      dirname = fn.eval('$PWD')
-    else
-      dirname = vim.fn.expand('%:p:h')
-    end 
-  end
+ dirname = dirname and dirname or vim.loop.cwd()
```

Also, please no global variables as it messes with user env. I guess it okay to have global that start with `ido_...` but `findfiles` and `fn` is so bad

**Comment by shoumodip** [comment]
Made the variables local, and changed the `findfiles` function to `ido_find_files()`. Also thanks for the tip! I didn't even know the `vim.loop.cwd()` function existed.

Lastly, glad you liked ido, although Emacs should get the praise for the well thought out interface. I merely ported it across platforms.
