### ISSUE TITLE
Namespace variables / functions using a module

### ISSUE THREAD

**Issue by alexanderjeurissen** [shoumodip/ido.nvim#10]
The extensibility of ido is it's strong suit, however the current global variables are a bit of a code smell.
We should consider if we can rewrite some of the code to use lua modules instead to prevent name clashes and further improve the extensibility.

e.g.

```lua
local ido = require 'ido'

ido.setup({
 fuzzy_matching = true,
 case_sensitive = false,
 minimal_mode = true,
 max_lines = 3
})

ido.complete({prompt = 'Choose: ', items = {'red', 'green', 'blue'}})
```

In the future this would open up further extensibility. For instance something emacs-like like the option to wrap some of the events (e.g. `advice` functions), or defining global overrides.

```lua
ido.advice_add('on_enter', function(s) 
  -- do things when `on_enter` occurs
end)

ido.advice_add('filter', function(s) 
  -- do things after `filter` is invoked
end)

ido.defun('on_enter', function(s) 
  -- replace on_enter globally 
end)
```

Which would allow plugin authors to write custom `extensions` that would enhance Ido.

**Comment by shoumodip** [comment]
This is epic. I had this exact idea the previous day! I was thinking about going a step further.

- Modules implementation in Ido for loading pre-defined functions like `find_files`
- Setup function which is *exactly* like you described here.

BTW don't you think an advice for the `on_enter` event is kinda redundant? I mean it is *meant* to be defined as a custom function which will be executed on entering. Why wrap an advice around it when we can change the thing itself.

Lastly I think I shall make minimal mode the only "mode". It may seem weird but trust me, the code for rendering in a window is *way* more complex and has a lot of bugs, mostly related to highlighting problems. Also there is this bug in NeoVim where the window and buffer numbers get jumbled up whenever a lua module is loaded. This has been creating a lot of problems in tracking the buffer and window number of Ido. It will also clear up a lot of code.

However as I have stated in #8, I am currently busy with approaching exams. It's a miracle I found time to check up on this. So expect no changes in a month. I'm really sorry, but that's how it is.

**Comment by alexanderjeurissen** [comment]
> This is epic. I had this exact idea the previous day! I was thinking about going a step further.
> 
> * Modules implementation in Ido for loading pre-defined functions like `find_files`
> * Setup function which is _exactly_ like you described here.
> 

> BTW don't you think an advice for the `on_enter` event is kinda redundant? I mean it is _meant_ to be defined as a custom function which will be executed on entering. Why wrap an advice around it when we can change the thing itself.
> 

Yeah it's kind of a bad example, but the idea was to allow global overrides or wrapping of several events, we'd have to figure out which ones make sense once we modularize.

> Lastly I think I shall make minimal mode the only "mode". It may seem weird but trust me, the code for rendering in a window is _way_ more complex and has a lot of bugs, mostly related to highlighting problems. Also there is this bug in NeoVim where the window and buffer numbers get jumbled up whenever a lua module is loaded. This has been creating a lot of problems in tracking the buffer and window number of Ido. It will also clear up a lot of code.

Tell me about it, I currently wrote my own custom floating window function to make buffers `floatable` such as help window / fzf. floating windows are a pain from my experience tracking window and buffer numbers is one thing, dealing with focus loss etc is even more painful. Like it's very easy to get windows that are `stuck` 

So big +1 for making minimal mode the default. It's also more in line with how the `minibuffer` works in emacs which is also just a echo area afaik (not entirely sure how it's implemented)

> 
> However as I have stated in #8, I am currently busy with approaching exams. It's a miracle I found time to check up on this. So expect no changes in a month. I'm really sorry, but that's how it is.

That fine, would you be open for PR's in the meantime ? I have some time to kill so I'll experiment with it in my fork regardless might as well create a PR.

**Comment by shoumodip** [comment]
Check out the latest changes

**Comment by alexanderjeurissen** [comment]
looks great, already created a simple `find files` using `ripgrep`

```lua
local ido = require "ido"
local main = require("ido.core.main")
local advice = require("ido.core.advice")

local set_keymap = vim.api.nvim_set_keymap

local COMMAND = 'rg --files --ignore --smart-case --hidden --follow --no-messages --ignore-file ~/.gitignore'

local find_files = {}

local function edit()
  local variables = ido.sandbox.variables
  local selected = ""

  -- Check if something matched or not
  if #variables.results > 0 then
    selected = variables.results[variables.selected][1]
  else
    -- The query is the thing we need to work with
    selected = variables.before_cursor..variables.after_cursor
  end

  main.exit()

  vim.cmd("edit " .. vim.loop.cwd() .. '/' .. selected)
end

local function prompt_title()
  local directory_name = vim.loop.cwd()
  local prompt_title =  " Find file: %s/"

  return string.format(prompt_title,
  string.gsub(vim.fn.resolve(directory_name), '^' .. os.getenv('HOME'), '~'))
end

find_files.run = function (layout)
  local title = 'Find file'

  advice.set("exit_on_accept_selected", "overwrite", edit, false)
  advice.set("single_result_after_accept_suggestion", "overwrite", edit, false)

  main.start({
    prompt = prompt_title(),
    layout = layout,
    items = vim.fn.systemlist(COMMAND),
  })
end

return find_files
```

which works great in vertical and horizontal modes 🕺 

<img width="1792" alt="Screen Shot 2021-02-23 at 10 05 14 PM" src="https://user-images.githubusercontent.com/1220084/108908175-4cd6a380-7623-11eb-8e33-7679ed94dcc8.png">
<img width="332" alt="Screen Shot 2021-02-23 at 10 04 56 PM" src="https://user-images.githubusercontent.com/1220084/108908182-4e07d080-7623-11eb-8a77-b657ac90b398.png">
