### ISSUE TITLE
New FZY based prefix calculation sometimes results in suffix suggestion

### ISSUE THREAD

**Issue by alexanderjeurissen** [shoumodip/ido.nvim#12]
### Context

Since the recent merge of the fzy based prefix calculation at times a `suffix` is suggested due to the way we utilize the matched `positions`  to calculate the prefix.

<img width="747" alt="Screen Shot 2021-02-17 at 7 29 21 PM" src="https://user-images.githubusercontent.com/1220084/108424899-0a375480-723a-11eb-95ad-f122fbfab716.png">

This is problematic as these can never be `completed`

**Comment by shoumodip** [comment]
This is how it is supposed to work. The problem lies in the name I gave it -- "prefix". I have changed the name `prefix` to `suggestion`. Now it should make sense.

**Comment by alexanderjeurissen** [comment]
yeah this now works as expected, with the fixed prefix prompt merging in the new version.

Closing this out.
