### ISSUE TITLE
next / prev match hotkeys broken in minimal_mode on new FZY implementation

### ISSUE THREAD

**Issue by alexanderjeurissen** [shoumodip/ido.nvim#13]
### Context

Since we merged the fzy branch it's no longer possible to switch between items using the next / previous item hotkeys `<C-n>` and `<C-p>`. 

#### Before pressing `<C-n>`
<img width="749" alt="image" src="https://user-images.githubusercontent.com/1220084/108425731-2982b180-723b-11eb-864d-692dff606db7.png">

#### After pressing `<C-n>`
<img width="1089" alt="Screen Shot 2021-02-18 at 10 44 08 PM" src="https://user-images.githubusercontent.com/1220084/108425639-0526d500-723b-11eb-8403-c8c0d53bfdd9.png">

### RCA

This happens due to the `ido_minimal_print` method receiving a `nil` value for the `text` parameter.
This then raises an exception when we hit the following line:

```lua
  minimal_text_length = minimal_text_length + text:len()
```

A workaround to at least get rid of the error is setting `''` as the default value for `text` parameter:

```diff
diff --git a/lua/ido.lua b/lua/ido.lua
index 42b24be..c52334e 100644
--- a/lua/ido.lua
+++ b/lua/ido.lua
@@ -477,6 +477,7 @@ end
 -- }}}
 -- Print the text in minimal mode -{{{
 local function ido_minimal_print(text, end_char)
+  text = text or ''
   minimal_text_length = minimal_text_length + text:len()
   end_char = end_char and end_char or ''
   local text_to_print = ''
```

However afterwards the switching between items still behaves odd as it renders an empty string as the second list item:

<img width="640" alt="image" src="https://user-images.githubusercontent.com/1220084/108426057-9138fc80-723b-11eb-9658-c8e1179bc4ac.png">

We need to figure out where we invoke the `ido_minimal_print` method with a potential `nil` value.

**Comment by shoumodip** [comment]
Fixed it

**Comment by alexanderjeurissen** [comment]
yes, this no longer is broken on the last commit.
