### ISSUE TITLE
option to have no space between statusline and ido

### ISSUE THREAD

**Issue by tami5** [shoumodip/ido.nvim#2]
It would be nice to have an option that eliminate the space between status line and ido
![](https://i.imgur.com/oWUHk7Y.png)
Also hide *Completion* tag :D 

Thanks

**Comment by shoumodip** [comment]
Please check it again. I changed the calculations (add 1 to the final result lol), so it should be placed _over_ the statusline, at least it does with me. Also by _Completions_, do you mean the `*Completions*` text that appears at the bottom?

**Comment by tami5** [comment]
Yes, I don't feel it's necessary at all, since the small popup is enough indication.

**Comment by tami5** [comment]
Now the ido popup hide the status line. It would be better to have ido above the statusline with no space between them as if its part of it

**Comment by shoumodip** [comment]
The statusline won't be overlapped from now on by default. If you *do* want it it to be hidden, I added in the `ido_overlap_statusline` option. Cheers :)

**Comment by tami5** [comment]
Thanks @shoumodip
