### ISSUE TITLE
Improve performance by wrapping narrowing function in CoRoutine

### ISSUE THREAD

**Issue by alexanderjeurissen** [shoumodip/ido.nvim#25]
### Context

Lua supports collaborative multithreading in the form of coroutines, which can help running intensive processes async.

ref: https://www.lua.org/manual/5.1/manual.html

Performance of ido can likely be further improved by wrapping it in coroutines.
Look at https://github.com/vijaymarupudi/nvim-fzf for an example on how coroutines can be utilized in this manner.

**Comment by shoumodip** [comment]
Using coroutines here can actually have a negative impact on performance. In a language like Go, where coroutines (sorry, *goroutines*) are **actually** asynchronous kernel threads, the performance is drastically improved. However in lua, coroutines are like, a way to track the state, almost like the State monad, if you know what I am talking about. Therefore, it is accompanied with an overhead of managing that paused state, the call stack, branching into instructions, etc.

What I mean to say is that using coroutines for performance benefits would have a negative impact. It would create an additional overhead, and slow down Ido even further than it already is. I'm not saying coroutines are bad, it's just they have their benefits in a slightly different context. And btw, I'm not just making an assumption about the performance implications. I am talking from personal experience. Coroutines do cause a noticeable slowdown.

All hope is not lost though. We could use the `luv` library, which is *actually* asynchronous, for achieving what you mentioned.

**Comment by shoumodip** [comment]
Since there has been no more activity on this issue for more than quite a few months, I am closing this.
