### ISSUE TITLE
Using command line space instead of popup

### ISSUE THREAD

**Issue by tami5** [shoumodip/ido.nvim#4]
Hey @shoumodip do you think its possible to have completion in the command line space rather in a popup? 

I think this will make it very minimal and perhaps more amazing. I think it could be provided as an option "minimal"

**Comment by shoumodip** [comment]
Added `ido_minimal_mode`. You are right, it looks really awesome.

**Comment by tami5** [comment]
Wow @shoumodip I didn't think it was achievable , well done, I'm eager to see how you did it. :D. One thing that I wish to find a solution for is hiding (or making it less obvious ) the cursor in the beginning of the command line. This is also apparent in other modes.
