### ISSUE TITLE
Bug where `minimal_mode` deletes current buffer when closing window

### ISSUE THREAD

**Issue by alexanderjeurissen** [shoumodip/ido.nvim#7]
# minimal config

```lua
require "ido"

ido_decorations['separator']   = ' | '
ido_decorations['matchstart']  = '{ '
ido_decorations['matchend']    = ' }'
ido_decorations['marker']      = ' -> '
ido_decorations['moreitems']   = '...'
ido_limit_lines                = true
ido_minimal_mode               = true
ido_overlap_statusline         = true
```

# Steps to reproduce

1. Open ido file browser using `<leader>.`
2. close the ido window by pressing `<esc`
3. second buffer/window is closed in addition to the `ido prompt buffer`

# screen recording

https://user-images.githubusercontent.com/1220084/107155846-032b5f00-697b-11eb-860d-2a93a1193a18.mov

# hypothesis

Probably a bug in the tracking of the buffer / window nr that are terminated.

**Comment by shoumodip** [comment]
Check it out now.

And FYI it was actually a bug in the `ido_close_window` function. It does not check whether the minimal mode is active or not. It was originally intended for the non-minimal version of ido and requires to delete the ido buffer when it closes. However in minimal mode, there is no "ido buffer", rendering happens in the echo area instead. Hence it just deletes the current buffer. Thought you would like to know. Cheers :)

**Comment by alexanderjeurissen** [comment]
@shoumodip that resolves the issue thx !
